resources:
- name: repo
  type: git
  icon: github
  source:
    uri: https://github.com/concourse/ctop
- name: postgres-11
  type: registry-image
  icon: elephant
  source:
    repository: postgres
    tag: 11-alpine
- name: go-1.14
  type: registry-image
  icon: language-go
  source:
    repository: golang
    tag: 1.14
jobs:
- name: test
  plan:
  - get: repo
    trigger: true
  - get: postgres-11
    params: {format: oci}
  - get: go-1.14
    params: {format: oci}
  - task: test
    privileged: true
    file: repo/ci/test.yml
