resources:
- name: repo
  type: git
  icon: github
  source:
    uri: https://github.com/jamieklassen/workloads
- name: postgres-11
  type: registry-image
  icon: elephant
  source:
    repository: postgres
    tag: 11-alpine
- name: go-1.14
  type: registry-image
  icon: language-go
  source:
    repository: golang
    tag: 1.14
jobs:
- name: test
  plan:
  - get: repo
    trigger: true
  - get: postgres-11
    params: {format: oci}
  - get: go-1.14
    params: {format: oci}
  - task: test
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: amidos/dcind}
      inputs:
      - name: postgres-11
      - name: go-1.14
      - name: repo
      run:
        path: bash
        args:
        - -exc
        - |
          source /docker-lib.sh
          start_docker
          docker load -i postgres-11/image.tar
          docker load -i go-1.14/image.tar
          docker-compose -f <(cat <<EOF
          version: '3'
          services:
            db:
              image: postgres:11-alpine
            tests:
              depends_on: [db]
              image: golang:1.14
              environment:
                DB_HOST: db
          EOF
          ) run -v $PWD/repo:/src -w /src tests go test ./...
